### ISSUE TITLE
[ISSUE] Unable to build sdk using make build:dist

### ISSUE THREAD

**Issue by disencd** [zscaler/zscaler-sdk-python#164]
**Description**
Unable to build sdk using make build:dist

**Reproduction**
A minimal code sample demonstrating the bug.

```
▶ make build:dist
python3 setup.py sdist bdist_wheel
python3: can't open file '/Users/disen/Repo/Personal/zscaler-sdk-python/setup.py': [Errno 2] No such file or directory
make: *** [build:dist] Error 2

```

**Expected behavior**
As per readme file, was expecting setup.py.

**Comment by willguibr** [comment]
@disencd 
Make file is outdated.
Please use poetry in order to build the SDK.
```sh
poetry build
```
This will create a folder called /dist. Navigate to this directory, and use pip to install the package.
BTW: There's i no need to compile the SDK locally. You can simply install it directly from PiPy like any other SDK unless you're attempting to play with the source code for your leisure. 
Please refer to the README page.

Zscaler DevRel
